server {
    # NGINX nasluchuje na domyslnym porcie 80
    listen 80;
    server_name localhost;

    location / {
        # Przekazywanie ruchu do aplikacji Go (Reverse Proxy)
        proxy_pass http://127.0.0.1:8080;
        
        # Przekazywanie oryginalnych naglowkow od klienta
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}